### ISSUE TITLE
Enable/Disable the notification 

### ISSUE THREAD

**Issue by aRn0D** [akeneo/michel-tag#14]
For now, notifications are sent the slack all the time, it is not useful during the development process. We should add an extra option the slack client to enable or disable it.

```yaml
notification:
    slack:
        akeneo:
            enable: true
            url: ''
            channel: '#migration-1-6'
            username: 'Support Team'
            emoji: ':akeneo:'
```
